In [ ]:
# from roboflow import Roboflow

# rf = Roboflow(api_key="eokejyt2yp6cXVBheCFe")
# project = rf.workspace("renuka").project("anpr-pojnu")
# version = project.version(8)

# dataset = version.download("yolov8")

# import requests
# dataset = requests.get('https://universe.roboflow.com/ds/2At90rGrWy?key=78ISxGpuM7')
# dataset.content

In [ ]:
from ultralytics import YOLO 

yolo = YOLO('yolov8n.pt')

results = yolo.train(data='dataset.yaml', epochs = 1) 

New https://pypi.org/project/ultralytics/8.3.28 available 😃 Update with 'pip install -U ultralytics'
Ultralytics 8.3.27 🚀 Python-3.12.1 torch-2.5.1 


ValueError: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: 0
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.


In [8]:
from ultralytics import YOLO

model = YOLO('runs/detect/train/weights/best.pt') 

# Run detection on a test image
results = model.predict(source='test.jpg', save=True, conf=0.25)

for result in results:
    boxes = result.boxes
    print(len(boxes))
    if len(boxes) > 0: 
        for box in boxes:
            x1, y1, x2, y2 = box.xyxy[0]
            class_id = int(box.cls)
            confidence = box.conf[0]
            class_name = model.names[class_id] if model.names else "Unknown"
            print(f"Class: {class_name}, Confidence: {confidence:.2f}, Box: [{x1}, {y1}, {x2}, {y2}]")
    else:
        print("No objects detected.")


image 1/1 /Users/denesh/Desktop/IIT-Chicago/Sem-2/ML/IIT-CS584-ML/ML/test.jpg: 544x640 (no detections), 121.6ms
Speed: 3.0ms preprocess, 121.6ms inference, 0.5ms postprocess per image at shape (1, 3, 544, 640)
Results saved to runs/detect/predict8
0
No objects detected.


In [ ]:
import torch

model_path = 'runs/detect/train/weights/best.pt'
checkpoint = torch.load(model_path)
model = checkpoint['model'].float()

input_data = torch.randn(1,  3,  960,  960)
print(input_data)
with torch.no_grad():
    output = model(input_data)


tensor([[[[ 1.1355, -1.3619, -2.2184,  ...,  0.8030, -2.5508, -0.9030],
          [-0.1311, -0.2903, -0.1507,  ..., -0.1154,  0.2774, -0.9949],
          [ 3.3879,  1.7268,  0.6038,  ..., -1.5384,  1.6107,  0.2658],
          ...,
          [ 0.5105,  1.6719,  0.5416,  ...,  0.5639, -0.9681,  0.0257],
          [-2.2170, -0.0533,  1.1489,  ...,  0.6862,  0.2481,  0.5660],
          [ 1.1653, -0.0240,  0.9190,  ..., -1.6663, -1.6096, -0.5336]],

         [[-0.1990, -0.9921, -0.7579,  ...,  0.5469, -1.4595,  0.5364],
          [-1.6132, -0.5210,  1.0908,  ...,  2.1427, -0.4855,  0.4634],
          [-0.2448, -1.0766, -1.1139,  ..., -0.6921,  1.8554,  0.7686],
          ...,
          [ 0.0647,  2.2982, -0.1627,  ..., -1.2781, -1.1100, -2.1298],
          [-1.6307,  0.2752,  1.1305,  ...,  1.6580,  0.0681, -0.5312],
          [ 0.4892, -1.0260, -0.9227,  ...,  1.0495, -0.9033,  0.6767]],

         [[-1.8592, -0.4260,  0.8088,  ..., -0.4237, -0.8939, -0.4920],
          [-0.4362,  0.1314, -

In [15]:
from ultralytics import YOLO
import torch
import cv2 
import numpy as np
import pathlib
import matplotlib.pyplot as plt


img = cv2.imread('/Users/denesh/Desktop/IIT-Chicago/Sem-2/ML/IIT-CS584-ML/ML/test.jpg')
model = YOLO('runs/detect/train/weights/best.pt')
results = model(img)
res_plotted = results[0].plot()
print(res_plotted)

for result in results:
    boxes = result.boxes  # Boxes object for bbox outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    probs = result.probs  
    print(boxes, masks, probs)


0: 544x640 (no detections), 72.6ms
Speed: 2.9ms preprocess, 72.6ms inference, 0.3ms postprocess per image at shape (1, 3, 544, 640)
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [254 253 255]
  [255 254 255]
  [255 254 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [254 253 255]
  [255 254 255]
  [255 254 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [254 253 255]
  [255 254 255]
  [255 254 255]]]
ultralytics.engine.results.Boxes object with attributes:

cls: tensor([])
conf: tensor([])
data: tensor([], size=(0, 6))
id: None
is_track: False
orig_shape: (686, 850)
shape: torch.Size([0, 6])
xywh: tensor([], size=(0, 4))
xywhn: tenso

In [ ]:
from ultralytics import YOLO
import os
from PIL import Image
import matplotlib.pyplot as plt

ROOT_DIR='/Users/denesh/Desktop/IIT-Chicago/Sem-2/ML/IIT-CS584-ML/ML/'

# Path to your custom-trained model weights
model_path = os.path.join(ROOT_DIR, 'runs/detect/train/weights/', 'last.pt')  # Or 'last.pt' if that's the latest

# Load your trained model
yolo = YOLO(model_path)

# ROOT_DIR='/Users/denesh/Desktop/IIT-Chicago/Sem-2/ML/IIT-CS584-ML/ML/datasets/valid/images/'
IMAGE_PATH = '6e772b68-a549-44e5-950e-4c376454c4e9___1557295d1474517501-toyota-innova-crysta-official-review-20160921_173216-jpg_jpeg.rf.e75c4eee8ee3a9197a00d67259aa26bd.jpg'
IMAGE_PATH='test.jpg'
# Path to the image you want to test
image_path = os.path.join(ROOT_DIR, IMAGE_PATH)

# Perform prediction on the image
results = yolo.predict(source=image_path, save=True)  # Saves output with bounding boxes

print(results)
print(results[0].names)
print(results[0].probs)

# Display the result using Matplotlib
predicted_image = Image.open(image_path)  # Reload image with annotations
plt.figure(figsize=(10, 10))
plt.imshow(predicted_image)
plt.axis('off')
plt.show()


In [15]:
ls

dataset/                       runs-20241109T232734Z-001.zip
dataset.ipynb                  test.jpg
dataset.yaml                   yolo11n.pt
datasets/                      yolov8n.pt
info.py


In [1]:
from ultralytics import YOLO
import cv2 

PATH = '' # '/Users/denesh/Desktop/IIT-Chicago/Sem-2/ML/IIT-CS584-ML/ML/runs/detect/train/weights/'
model = YOLO(PATH + 'best.pt')
# camera = cv2.VideoCapture(0)


# while True:
#     ret, frame = camera.read()
#     if not ret:
#         print("failed to grab frame")
#         break
#     cv2.imshow("test", frame)

    # k = cv2.waitKey(1)
    # if k%256 == 27:
    #     # ESC pressed
    #     print("Escape hit, closing...")
    #     break
    # elif k%256 == 32:
    #     # SPACE pressed
 
img = cv2.imread('test.jpg')
outs = model.predict(img, show=True)
    # img_counter += 1

# camera.release()

2024-11-09 20:10:11.843 Python[47560:4110781] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-09 20:10:11.843 Python[47560:4110781] +[IMKInputSession subclass]: chose IMKInputSession_Modern


0: 384x640 (no detections), 145.0ms
Speed: 17.6ms preprocess, 145.0ms inference, 0.4ms postprocess per image at shape (1, 3, 384, 640)
